/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QColumnView>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QStackedWidget *stackedWidget;
    QWidget *N0pageRFID;
    QLabel *label;
    QPushButton *pushButtonSWER;
    QPushButton *pushButtonFIN;
    QPushButton *pushButtonBR;
    QWidget *N1pagePIN;
    QPushButton *pushButton1;
    QPushButton *pushButton3;
    QPushButton *pushButton2;
    QPushButton *pushButton9;
    QPushButton *pushButtonCancel;
    QPushButton *pushButton8;
    QPushButton *pushButton4;
    QPushButton *pushButton5;
    QPushButton *pushButton7;
    QLabel *passwordLabel;
    QPushButton *pushButtonLogin;
    QPushButton *pushButton6;
    QLabel *attemptsLabelNumber;
    QLabel *attemptsLabelText;
    QPushButton *pushButtonSWER_2;
    QPushButton *pushButtonBR_2;
    QPushButton *pushButtonFIN_2;
    QWidget *N2pageWithdrawalConfirm;
    QColumnView *columnView_2;
    QLabel *label_2;
    QLabel *labelWithdrawalConfirm;
    QPushButton *pushButtonWithdrawalConfirmNo;
    QPushButton *pushButtonWithdrawalConfirmYes;
    QLabel *labelWithdrawalConfirm_2;
    QLabel *labelWithdrawalSelectedAccount;
    QWidget *N3pageMENU;
    QPushButton *pushButtonWithdrawalMENU;
    QPushButton *pushButtonTransactionHistoryMENU;
    QPushButton *pushButtonAccountsMENU;
    QPushButton *pushButtonFundTransferMENU;
    QPushButton *pushButtonLogout;
    QPushButton *pushButtonSWER_3;
    QPushButton *pushButtonFIN_3;
    QPushButton *pushButtonBR_3;
    QWidget *N4pageTransactionHistory;
    QLabel *labelTransactionHistory;
    QPushButton *pushButtonTransactionHistoryBack;
    QTableWidget *tableWidget;
    QWidget *N5pageWithdrawal;
    QLabel *label_3;
    QColumnView *columnView;
    QPushButton *pushButtonWithdrawal20;
    QPushButton *pushButtonWithdrawal50;
    QPushButton *pushButtonWithdrawal100;
    QPushButton *pushButtonWithdrawal500;
    QPushButton *pushButtonWithdrawal200;
    QPushButton *pushButtonWithdrawal150;
    QPushButton *pushButtonWithdrawalConfirm;
    QPushButton *pushButtonWithdrawalCancel;
    QLabel *labelWithdrawalAmount;
    QPushButton *pushButtonWithdrawalBack;
    QLabel *label_9;
    QListWidget *listWidgetWithdrawal;
    QLabel *labelSelectedAccountWithdrawal;
    QWidget *N6pageFundTransfer;
    QListWidget *listWidgetFundTransfer;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *lineEditAccount1;
    QLineEdit *lineEditAccount2;
    QToolButton *toolButton;
    QPushButton *pushButtonFundTransferBack;
    QPushButton *pushButtonFundTransfer_3;
    QPushButton *pushButtonFundTransfer_1;
    QPushButton *pushButtonFundTransfer_2;
    QPushButton *pushButtonFundTransfer_5;
    QPushButton *pushButtonFundTransfer_6;
    QPushButton *pushButtonFundTransfer_4;
    QPushButton *pushButtonFundTransfer_8;
    QPushButton *pushButtonFundTransfer_9;
    QPushButton *pushButtonFundTransfer_7;
    QLineEdit *lineEditTransferAmount;
    QPushButton *pushButtonFundTransfer_return;
    QPushButton *pushButtonFundTransfer_cancel;
    QPushButton *pushButtonFundTransfer_confirm;
    QPushButton *pushButtonFundTransfer_0;
    QPushButton *pushButtonTransferFundsSwap;
    QWidget *N7pageAccounts;
    QLabel *label_6;
    QPushButton *pushButtonAccountsBack;
    QTableWidget *tableWidgetAccounts;
    QWidget *N8pageFundTransferConfirm;
    QColumnView *columnView_4;
    QLabel *label_7;
    QLabel *labelTransferAmount;
    QLabel *label_8;
    QLabel *label_Account1;
    QLabel *label_10;
    QLabel *label_Account2;
    QPushButton *pushButtonFundTransferConfirmYes;
    QPushButton *pushButtonFundTransferConfirmNo;
    QFrame *frame;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1600, 900);
        QFont font;
        font.setPointSize(8);
        MainWindow->setFont(font);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(30, -120, 2471, 971));
        stackedWidget->setAutoFillBackground(false);
        N0pageRFID = new QWidget();
        N0pageRFID->setObjectName(QStringLiteral("N0pageRFID"));
        label = new QLabel(N0pageRFID);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(490, 350, 891, 101));
        QFont font1;
        font1.setPointSize(22);
        label->setFont(font1);
        pushButtonSWER = new QPushButton(N0pageRFID);
        pushButtonSWER->setObjectName(QStringLiteral("pushButtonSWER"));
        pushButtonSWER->setGeometry(QRect(270, 120, 101, 61));
        QIcon icon;
        icon.addFile(QStringLiteral(":/new/prefix1/flagswe.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButtonSWER->setIcon(icon);
        pushButtonSWER->setIconSize(QSize(100, 100));
        pushButtonFIN = new QPushButton(N0pageRFID);
        pushButtonFIN->setObjectName(QStringLiteral("pushButtonFIN"));
        pushButtonFIN->setGeometry(QRect(150, 120, 101, 61));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/new/prefix1/flagfin.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButtonFIN->setIcon(icon1);
        pushButtonFIN->setIconSize(QSize(100, 100));
        pushButtonBR = new QPushButton(N0pageRFID);
        pushButtonBR->setObjectName(QStringLiteral("pushButtonBR"));
        pushButtonBR->setGeometry(QRect(30, 120, 101, 61));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/new/prefix1/flagbr.jpg"), QSize(), QIcon::Normal, QIcon::Off);
        pushButtonBR->setIcon(icon2);
        pushButtonBR->setIconSize(QSize(100, 100));
        stackedWidget->addWidget(N0pageRFID);
        N1pagePIN = new QWidget();
        N1pagePIN->setObjectName(QStringLiteral("N1pagePIN"));
        pushButton1 = new QPushButton(N1pagePIN);
        pushButton1->setObjectName(QStringLiteral("pushButton1"));
        pushButton1->setGeometry(QRect(550, 290, 161, 141));
        QFont font2;
        font2.setPointSize(35);
        pushButton1->setFont(font2);
        pushButton3 = new QPushButton(N1pagePIN);
        pushButton3->setObjectName(QStringLiteral("pushButton3"));
        pushButton3->setGeometry(QRect(950, 290, 161, 141));
        pushButton3->setFont(font2);
        pushButton2 = new QPushButton(N1pagePIN);
        pushButton2->setObjectName(QStringLiteral("pushButton2"));
        pushButton2->setGeometry(QRect(750, 290, 161, 141));
        pushButton2->setFont(font2);
        pushButton9 = new QPushButton(N1pagePIN);
        pushButton9->setObjectName(QStringLiteral("pushButton9"));
        pushButton9->setGeometry(QRect(950, 610, 161, 141));
        pushButton9->setFont(font2);
        pushButtonCancel = new QPushButton(N1pagePIN);
        pushButtonCancel->setObjectName(QStringLiteral("pushButtonCancel"));
        pushButtonCancel->setGeometry(QRect(550, 770, 221, 151));
        QFont font3;
        font3.setPointSize(25);
        pushButtonCancel->setFont(font3);
        pushButton8 = new QPushButton(N1pagePIN);
        pushButton8->setObjectName(QStringLiteral("pushButton8"));
        pushButton8->setGeometry(QRect(750, 610, 161, 141));
        pushButton8->setFont(font2);
        pushButton4 = new QPushButton(N1pagePIN);
        pushButton4->setObjectName(QStringLiteral("pushButton4"));
        pushButton4->setGeometry(QRect(550, 450, 161, 141));
        pushButton4->setFont(font2);
        pushButton5 = new QPushButton(N1pagePIN);
        pushButton5->setObjectName(QStringLiteral("pushButton5"));
        pushButton5->setGeometry(QRect(750, 450, 161, 141));
        pushButton5->setFont(font2);
        pushButton7 = new QPushButton(N1pagePIN);
        pushButton7->setObjectName(QStringLiteral("pushButton7"));
        pushButton7->setGeometry(QRect(550, 610, 161, 141));
        pushButton7->setFont(font2);
        passwordLabel = new QLabel(N1pagePIN);
        passwordLabel->setObjectName(QStringLiteral("passwordLabel"));
        passwordLabel->setGeometry(QRect(550, 200, 561, 71));
        QFont font4;
        font4.setPointSize(50);
        passwordLabel->setFont(font4);
        passwordLabel->setFrameShape(QFrame::WinPanel);
        pushButtonLogin = new QPushButton(N1pagePIN);
        pushButtonLogin->setObjectName(QStringLiteral("pushButtonLogin"));
        pushButtonLogin->setGeometry(QRect(810, 770, 301, 151));
        pushButtonLogin->setFont(font3);
        pushButton6 = new QPushButton(N1pagePIN);
        pushButton6->setObjectName(QStringLiteral("pushButton6"));
        pushButton6->setGeometry(QRect(950, 450, 161, 141));
        pushButton6->setFont(font2);
        attemptsLabelNumber = new QLabel(N1pagePIN);
        attemptsLabelNumber->setObjectName(QStringLiteral("attemptsLabelNumber"));
        attemptsLabelNumber->setGeometry(QRect(550, 150, 41, 41));
        QFont font5;
        font5.setPointSize(18);
        attemptsLabelNumber->setFont(font5);
        attemptsLabelText = new QLabel(N1pagePIN);
        attemptsLabelText->setObjectName(QStringLiteral("attemptsLabelText"));
        attemptsLabelText->setGeometry(QRect(600, 150, 751, 41));
        attemptsLabelText->setFont(font5);
        pushButtonSWER_2 = new QPushButton(N1pagePIN);
        pushButtonSWER_2->setObjectName(QStringLiteral("pushButtonSWER_2"));
        pushButtonSWER_2->setGeometry(QRect(270, 120, 101, 61));
        pushButtonSWER_2->setIcon(icon);
        pushButtonSWER_2->setIconSize(QSize(100, 100));
        pushButtonBR_2 = new QPushButton(N1pagePIN);
        pushButtonBR_2->setObjectName(QStringLiteral("pushButtonBR_2"));
        pushButtonBR_2->setGeometry(QRect(30, 120, 101, 61));
        pushButtonBR_2->setIcon(icon2);
        pushButtonBR_2->setIconSize(QSize(100, 100));
        pushButtonFIN_2 = new QPushButton(N1pagePIN);
        pushButtonFIN_2->setObjectName(QStringLiteral("pushButtonFIN_2"));
        pushButtonFIN_2->setGeometry(QRect(150, 120, 101, 61));
        pushButtonFIN_2->setIcon(icon1);
        pushButtonFIN_2->setIconSize(QSize(100, 100));
        stackedWidget->addWidget(N1pagePIN);
        N2pageWithdrawalConfirm = new QWidget();
        N2pageWithdrawalConfirm->setObjectName(QStringLiteral("N2pageWithdrawalConfirm"));
        columnView_2 = new QColumnView(N2pageWithdrawalConfirm);
        columnView_2->setObjectName(QStringLiteral("columnView_2"));
        columnView_2->setGeometry(QRect(410, 390, 721, 291));
        label_2 = new QLabel(N2pageWithdrawalConfirm);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(430, 410, 691, 61));
        label_2->setFont(font3);
        labelWithdrawalConfirm = new QLabel(N2pageWithdrawalConfirm);
        labelWithdrawalConfirm->setObjectName(QStringLiteral("labelWithdrawalConfirm"));
        labelWithdrawalConfirm->setGeometry(QRect(710, 490, 211, 61));
        labelWithdrawalConfirm->setFont(font3);
        pushButtonWithdrawalConfirmNo = new QPushButton(N2pageWithdrawalConfirm);
        pushButtonWithdrawalConfirmNo->setObjectName(QStringLiteral("pushButtonWithdrawalConfirmNo"));
        pushButtonWithdrawalConfirmNo->setGeometry(QRect(860, 710, 271, 171));
        QFont font6;
        font6.setPointSize(30);
        pushButtonWithdrawalConfirmNo->setFont(font6);
        pushButtonWithdrawalConfirmYes = new QPushButton(N2pageWithdrawalConfirm);
        pushButtonWithdrawalConfirmYes->setObjectName(QStringLiteral("pushButtonWithdrawalConfirmYes"));
        pushButtonWithdrawalConfirmYes->setGeometry(QRect(410, 710, 271, 171));
        pushButtonWithdrawalConfirmYes->setFont(font6);
        labelWithdrawalConfirm_2 = new QLabel(N2pageWithdrawalConfirm);
        labelWithdrawalConfirm_2->setObjectName(QStringLiteral("labelWithdrawalConfirm_2"));
        labelWithdrawalConfirm_2->setGeometry(QRect(590, 570, 181, 61));
        labelWithdrawalConfirm_2->setFont(font5);
        labelWithdrawalSelectedAccount = new QLabel(N2pageWithdrawalConfirm);
        labelWithdrawalSelectedAccount->setObjectName(QStringLiteral("labelWithdrawalSelectedAccount"));
        labelWithdrawalSelectedAccount->setGeometry(QRect(780, 570, 181, 61));
        labelWithdrawalSelectedAccount->setFont(font5);
        stackedWidget->addWidget(N2pageWithdrawalConfirm);
        N3pageMENU = new QWidget();
        N3pageMENU->setObjectName(QStringLiteral("N3pageMENU"));
        pushButtonWithdrawalMENU = new QPushButton(N3pageMENU);
        pushButtonWithdrawalMENU->setObjectName(QStringLiteral("pushButtonWithdrawalMENU"));
        pushButtonWithdrawalMENU->setGeometry(QRect(370, 200, 521, 301));
        pushButtonWithdrawalMENU->setFont(font6);
        pushButtonTransactionHistoryMENU = new QPushButton(N3pageMENU);
        pushButtonTransactionHistoryMENU->setObjectName(QStringLiteral("pushButtonTransactionHistoryMENU"));
        pushButtonTransactionHistoryMENU->setGeometry(QRect(930, 200, 521, 301));
        pushButtonTransactionHistoryMENU->setFont(font6);
        pushButtonAccountsMENU = new QPushButton(N3pageMENU);
        pushButtonAccountsMENU->setObjectName(QStringLiteral("pushButtonAccountsMENU"));
        pushButtonAccountsMENU->setGeometry(QRect(930, 530, 521, 301));
        pushButtonAccountsMENU->setFont(font6);
        pushButtonFundTransferMENU = new QPushButton(N3pageMENU);
        pushButtonFundTransferMENU->setObjectName(QStringLiteral("pushButtonFundTransferMENU"));
        pushButtonFundTransferMENU->setGeometry(QRect(370, 530, 521, 301));
        pushButtonFundTransferMENU->setFont(font6);
        pushButtonLogout = new QPushButton(N3pageMENU);
        pushButtonLogout->setObjectName(QStringLiteral("pushButtonLogout"));
        pushButtonLogout->setGeometry(QRect(10, 840, 311, 91));
        pushButtonLogout->setFont(font6);
        pushButtonSWER_3 = new QPushButton(N3pageMENU);
        pushButtonSWER_3->setObjectName(QStringLiteral("pushButtonSWER_3"));
        pushButtonSWER_3->setGeometry(QRect(270, 120, 101, 61));
        pushButtonSWER_3->setIcon(icon);
        pushButtonSWER_3->setIconSize(QSize(100, 100));
        pushButtonFIN_3 = new QPushButton(N3pageMENU);
        pushButtonFIN_3->setObjectName(QStringLiteral("pushButtonFIN_3"));
        pushButtonFIN_3->setGeometry(QRect(150, 120, 101, 61));
        pushButtonFIN_3->setIcon(icon1);
        pushButtonFIN_3->setIconSize(QSize(100, 100));
        pushButtonBR_3 = new QPushButton(N3pageMENU);
        pushButtonBR_3->setObjectName(QStringLiteral("pushButtonBR_3"));
        pushButtonBR_3->setGeometry(QRect(30, 120, 101, 61));
        pushButtonBR_3->setIcon(icon2);
        pushButtonBR_3->setIconSize(QSize(100, 100));
        stackedWidget->addWidget(N3pageMENU);
        N4pageTransactionHistory = new QWidget();
        N4pageTransactionHistory->setObjectName(QStringLiteral("N4pageTransactionHistory"));
        labelTransactionHistory = new QLabel(N4pageTransactionHistory);
        labelTransactionHistory->setObjectName(QStringLiteral("labelTransactionHistory"));
        labelTransactionHistory->setGeometry(QRect(610, 100, 511, 71));
        labelTransactionHistory->setFont(font6);
        pushButtonTransactionHistoryBack = new QPushButton(N4pageTransactionHistory);
        pushButtonTransactionHistoryBack->setObjectName(QStringLiteral("pushButtonTransactionHistoryBack"));
        pushButtonTransactionHistoryBack->setGeometry(QRect(10, 850, 211, 91));
        pushButtonTransactionHistoryBack->setFont(font3);
        tableWidget = new QTableWidget(N4pageTransactionHistory);
        if (tableWidget->columnCount() < 3)
            tableWidget->setColumnCount(3);
        if (tableWidget->rowCount() < 20)
            tableWidget->setRowCount(20);
        tableWidget->setObjectName(QStringLiteral("tableWidget"));
        tableWidget->setGeometry(QRect(180, 200, 1361, 631));
        QFont font7;
        font7.setPointSize(15);
        tableWidget->setFont(font7);
        tableWidget->setFrameShape(QFrame::StyledPanel);
        tableWidget->setFrameShadow(QFrame::Sunken);
        tableWidget->setLineWidth(2);
        tableWidget->setMidLineWidth(2);
        tableWidget->setShowGrid(true);
        tableWidget->setRowCount(20);
        tableWidget->setColumnCount(3);
        stackedWidget->addWidget(N4pageTransactionHistory);
        N5pageWithdrawal = new QWidget();
        N5pageWithdrawal->setObjectName(QStringLiteral("N5pageWithdrawal"));
        label_3 = new QLabel(N5pageWithdrawal);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(1120, 290, 341, 91));
        label_3->setFont(font3);
        columnView = new QColumnView(N5pageWithdrawal);
        columnView->setObjectName(QStringLiteral("columnView"));
        columnView->setGeometry(QRect(270, 120, 1191, 821));
        pushButtonWithdrawal20 = new QPushButton(N5pageWithdrawal);
        pushButtonWithdrawal20->setObjectName(QStringLiteral("pushButtonWithdrawal20"));
        pushButtonWithdrawal20->setGeometry(QRect(290, 300, 311, 181));
        pushButtonWithdrawal20->setFont(font2);
        pushButtonWithdrawal50 = new QPushButton(N5pageWithdrawal);
        pushButtonWithdrawal50->setObjectName(QStringLiteral("pushButtonWithdrawal50"));
        pushButtonWithdrawal50->setGeometry(QRect(290, 500, 311, 181));
        pushButtonWithdrawal50->setFont(font2);
        pushButtonWithdrawal100 = new QPushButton(N5pageWithdrawal);
        pushButtonWithdrawal100->setObjectName(QStringLiteral("pushButtonWithdrawal100"));
        pushButtonWithdrawal100->setGeometry(QRect(290, 700, 311, 181));
        pushButtonWithdrawal100->setFont(font2);
        pushButtonWithdrawal500 = new QPushButton(N5pageWithdrawal);
        pushButtonWithdrawal500->setObjectName(QStringLiteral("pushButtonWithdrawal500"));
        pushButtonWithdrawal500->setGeometry(QRect(710, 700, 311, 181));
        pushButtonWithdrawal500->setFont(font2);
        pushButtonWithdrawal200 = new QPushButton(N5pageWithdrawal);
        pushButtonWithdrawal200->setObjectName(QStringLiteral("pushButtonWithdrawal200"));
        pushButtonWithdrawal200->setGeometry(QRect(710, 500, 311, 181));
        pushButtonWithdrawal200->setFont(font2);
        pushButtonWithdrawal150 = new QPushButton(N5pageWithdrawal);
        pushButtonWithdrawal150->setObjectName(QStringLiteral("pushButtonWithdrawal150"));
        pushButtonWithdrawal150->setGeometry(QRect(710, 300, 311, 181));
        pushButtonWithdrawal150->setFont(font2);
        pushButtonWithdrawalConfirm = new QPushButton(N5pageWithdrawal);
        pushButtonWithdrawalConfirm->setObjectName(QStringLiteral("pushButtonWithdrawalConfirm"));
        pushButtonWithdrawalConfirm->setGeometry(QRect(1150, 740, 281, 141));
        pushButtonWithdrawalConfirm->setFont(font2);
        pushButtonWithdrawalCancel = new QPushButton(N5pageWithdrawal);
        pushButtonWithdrawalCancel->setObjectName(QStringLiteral("pushButtonWithdrawalCancel"));
        pushButtonWithdrawalCancel->setGeometry(QRect(1150, 560, 281, 111));
        pushButtonWithdrawalCancel->setFont(font2);
        labelWithdrawalAmount = new QLabel(N5pageWithdrawal);
        labelWithdrawalAmount->setObjectName(QStringLiteral("labelWithdrawalAmount"));
        labelWithdrawalAmount->setGeometry(QRect(1150, 390, 281, 91));
        labelWithdrawalAmount->setFont(font2);
        labelWithdrawalAmount->setFrameShape(QFrame::WinPanel);
        pushButtonWithdrawalBack = new QPushButton(N5pageWithdrawal);
        pushButtonWithdrawalBack->setObjectName(QStringLiteral("pushButtonWithdrawalBack"));
        pushButtonWithdrawalBack->setGeometry(QRect(10, 840, 211, 101));
        pushButtonWithdrawalBack->setFont(font6);
        label_9 = new QLabel(N5pageWithdrawal);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(280, 120, 371, 91));
        label_9->setFont(font3);
        listWidgetWithdrawal = new QListWidget(N5pageWithdrawal);
        listWidgetWithdrawal->setObjectName(QStringLiteral("listWidgetWithdrawal"));
        listWidgetWithdrawal->setGeometry(QRect(630, 130, 391, 141));
        QFont font8;
        font8.setPointSize(20);
        listWidgetWithdrawal->setFont(font8);
        labelSelectedAccountWithdrawal = new QLabel(N5pageWithdrawal);
        labelSelectedAccountWithdrawal->setObjectName(QStringLiteral("labelSelectedAccountWithdrawal"));
        labelSelectedAccountWithdrawal->setGeometry(QRect(1050, 130, 271, 61));
        labelSelectedAccountWithdrawal->setFont(font3);
        labelSelectedAccountWithdrawal->setFrameShape(QFrame::WinPanel);
        stackedWidget->addWidget(N5pageWithdrawal);
        columnView->raise();
        label_3->raise();
        pushButtonWithdrawal20->raise();
        pushButtonWithdrawal50->raise();
        pushButtonWithdrawal100->raise();
        pushButtonWithdrawal500->raise();
        pushButtonWithdrawal200->raise();
        pushButtonWithdrawal150->raise();
        pushButtonWithdrawalConfirm->raise();
        pushButtonWithdrawalCancel->raise();
        labelWithdrawalAmount->raise();
        pushButtonWithdrawalBack->raise();
        label_9->raise();
        listWidgetWithdrawal->raise();
        labelSelectedAccountWithdrawal->raise();
        N6pageFundTransfer = new QWidget();
        N6pageFundTransfer->setObjectName(QStringLiteral("N6pageFundTransfer"));
        listWidgetFundTransfer = new QListWidget(N6pageFundTransfer);
        listWidgetFundTransfer->setObjectName(QStringLiteral("listWidgetFundTransfer"));
        listWidgetFundTransfer->setGeometry(QRect(500, 230, 661, 161));
        listWidgetFundTransfer->setFont(font8);
        label_4 = new QLabel(N6pageFundTransfer);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(650, 110, 581, 61));
        label_4->setFont(font3);
        label_5 = new QLabel(N6pageFundTransfer);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(560, 180, 261, 41));
        QFont font9;
        font9.setPointSize(16);
        label_5->setFont(font9);
        lineEditAccount1 = new QLineEdit(N6pageFundTransfer);
        lineEditAccount1->setObjectName(QStringLiteral("lineEditAccount1"));
        lineEditAccount1->setGeometry(QRect(500, 440, 291, 41));
        lineEditAccount1->setFont(font8);
        lineEditAccount2 = new QLineEdit(N6pageFundTransfer);
        lineEditAccount2->setObjectName(QStringLiteral("lineEditAccount2"));
        lineEditAccount2->setGeometry(QRect(870, 440, 291, 41));
        lineEditAccount2->setFont(font8);
        toolButton = new QToolButton(N6pageFundTransfer);
        toolButton->setObjectName(QStringLiteral("toolButton"));
        toolButton->setGeometry(QRect(810, 400, 41, 41));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/new/prefix1/transferArrow.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton->setIcon(icon3);
        toolButton->setIconSize(QSize(50, 50));
        pushButtonFundTransferBack = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransferBack->setObjectName(QStringLiteral("pushButtonFundTransferBack"));
        pushButtonFundTransferBack->setGeometry(QRect(10, 860, 171, 81));
        pushButtonFundTransferBack->setFont(font8);
        pushButtonFundTransfer_3 = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_3->setObjectName(QStringLiteral("pushButtonFundTransfer_3"));
        pushButtonFundTransfer_3->setGeometry(QRect(840, 600, 181, 91));
        pushButtonFundTransfer_3->setFont(font2);
        pushButtonFundTransfer_1 = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_1->setObjectName(QStringLiteral("pushButtonFundTransfer_1"));
        pushButtonFundTransfer_1->setGeometry(QRect(400, 600, 181, 91));
        pushButtonFundTransfer_1->setFont(font2);
        pushButtonFundTransfer_2 = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_2->setObjectName(QStringLiteral("pushButtonFundTransfer_2"));
        pushButtonFundTransfer_2->setGeometry(QRect(620, 600, 181, 91));
        pushButtonFundTransfer_2->setFont(font2);
        pushButtonFundTransfer_5 = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_5->setObjectName(QStringLiteral("pushButtonFundTransfer_5"));
        pushButtonFundTransfer_5->setGeometry(QRect(620, 720, 181, 91));
        pushButtonFundTransfer_5->setFont(font2);
        pushButtonFundTransfer_6 = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_6->setObjectName(QStringLiteral("pushButtonFundTransfer_6"));
        pushButtonFundTransfer_6->setGeometry(QRect(840, 720, 181, 91));
        pushButtonFundTransfer_6->setFont(font2);
        pushButtonFundTransfer_4 = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_4->setObjectName(QStringLiteral("pushButtonFundTransfer_4"));
        pushButtonFundTransfer_4->setGeometry(QRect(400, 720, 181, 91));
        pushButtonFundTransfer_4->setFont(font2);
        pushButtonFundTransfer_8 = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_8->setObjectName(QStringLiteral("pushButtonFundTransfer_8"));
        pushButtonFundTransfer_8->setGeometry(QRect(620, 830, 181, 91));
        pushButtonFundTransfer_8->setFont(font2);
        pushButtonFundTransfer_9 = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_9->setObjectName(QStringLiteral("pushButtonFundTransfer_9"));
        pushButtonFundTransfer_9->setGeometry(QRect(840, 830, 181, 91));
        pushButtonFundTransfer_9->setFont(font2);
        pushButtonFundTransfer_7 = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_7->setObjectName(QStringLiteral("pushButtonFundTransfer_7"));
        pushButtonFundTransfer_7->setGeometry(QRect(400, 830, 181, 91));
        pushButtonFundTransfer_7->setFont(font2);
        lineEditTransferAmount = new QLineEdit(N6pageFundTransfer);
        lineEditTransferAmount->setObjectName(QStringLiteral("lineEditTransferAmount"));
        lineEditTransferAmount->setGeometry(QRect(640, 530, 371, 51));
        lineEditTransferAmount->setFont(font8);
        pushButtonFundTransfer_return = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_return->setObjectName(QStringLiteral("pushButtonFundTransfer_return"));
        pushButtonFundTransfer_return->setGeometry(QRect(1060, 600, 181, 91));
        pushButtonFundTransfer_return->setFont(font2);
        pushButtonFundTransfer_cancel = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_cancel->setObjectName(QStringLiteral("pushButtonFundTransfer_cancel"));
        pushButtonFundTransfer_cancel->setGeometry(QRect(1290, 720, 181, 91));
        pushButtonFundTransfer_cancel->setFont(font1);
        pushButtonFundTransfer_confirm = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_confirm->setObjectName(QStringLiteral("pushButtonFundTransfer_confirm"));
        pushButtonFundTransfer_confirm->setGeometry(QRect(1290, 830, 181, 91));
        pushButtonFundTransfer_confirm->setFont(font1);
        pushButtonFundTransfer_0 = new QPushButton(N6pageFundTransfer);
        pushButtonFundTransfer_0->setObjectName(QStringLiteral("pushButtonFundTransfer_0"));
        pushButtonFundTransfer_0->setGeometry(QRect(1060, 830, 181, 91));
        pushButtonFundTransfer_0->setFont(font2);
        pushButtonTransferFundsSwap = new QPushButton(N6pageFundTransfer);
        pushButtonTransferFundsSwap->setObjectName(QStringLiteral("pushButtonTransferFundsSwap"));
        pushButtonTransferFundsSwap->setGeometry(QRect(790, 440, 81, 41));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/new/prefix1/transfer.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButtonTransferFundsSwap->setIcon(icon4);
        pushButtonTransferFundsSwap->setIconSize(QSize(50, 40));
        stackedWidget->addWidget(N6pageFundTransfer);
        N7pageAccounts = new QWidget();
        N7pageAccounts->setObjectName(QStringLiteral("N7pageAccounts"));
        label_6 = new QLabel(N7pageAccounts);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(600, 280, 271, 61));
        label_6->setFont(font2);
        pushButtonAccountsBack = new QPushButton(N7pageAccounts);
        pushButtonAccountsBack->setObjectName(QStringLiteral("pushButtonAccountsBack"));
        pushButtonAccountsBack->setGeometry(QRect(20, 850, 151, 91));
        pushButtonAccountsBack->setFont(font8);
        tableWidgetAccounts = new QTableWidget(N7pageAccounts);
        if (tableWidgetAccounts->columnCount() < 3)
            tableWidgetAccounts->setColumnCount(3);
        if (tableWidgetAccounts->rowCount() < 6)
            tableWidgetAccounts->setRowCount(6);
        tableWidgetAccounts->setObjectName(QStringLiteral("tableWidgetAccounts"));
        tableWidgetAccounts->setGeometry(QRect(360, 410, 781, 261));
        tableWidgetAccounts->setFont(font7);
        tableWidgetAccounts->setRowCount(6);
        tableWidgetAccounts->setColumnCount(3);
        stackedWidget->addWidget(N7pageAccounts);
        N8pageFundTransferConfirm = new QWidget();
        N8pageFundTransferConfirm->setObjectName(QStringLiteral("N8pageFundTransferConfirm"));
        columnView_4 = new QColumnView(N8pageFundTransferConfirm);
        columnView_4->setObjectName(QStringLiteral("columnView_4"));
        columnView_4->setGeometry(QRect(320, 360, 1031, 541));
        label_7 = new QLabel(N8pageFundTransferConfirm);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(590, 390, 561, 71));
        label_7->setFont(font8);
        labelTransferAmount = new QLabel(N8pageFundTransferConfirm);
        labelTransferAmount->setObjectName(QStringLiteral("labelTransferAmount"));
        labelTransferAmount->setGeometry(QRect(750, 490, 481, 71));
        labelTransferAmount->setFont(font8);
        label_8 = new QLabel(N8pageFundTransferConfirm);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(340, 620, 181, 71));
        label_8->setFont(font9);
        label_Account1 = new QLabel(N8pageFundTransferConfirm);
        label_Account1->setObjectName(QStringLiteral("label_Account1"));
        label_Account1->setGeometry(QRect(550, 620, 281, 71));
        label_Account1->setFont(font9);
        label_10 = new QLabel(N8pageFundTransferConfirm);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(840, 620, 171, 71));
        label_10->setFont(font9);
        label_Account2 = new QLabel(N8pageFundTransferConfirm);
        label_Account2->setObjectName(QStringLiteral("label_Account2"));
        label_Account2->setGeometry(QRect(1020, 620, 321, 71));
        label_Account2->setFont(font9);
        pushButtonFundTransferConfirmYes = new QPushButton(N8pageFundTransferConfirm);
        pushButtonFundTransferConfirmYes->setObjectName(QStringLiteral("pushButtonFundTransferConfirmYes"));
        pushButtonFundTransferConfirmYes->setGeometry(QRect(340, 790, 221, 91));
        pushButtonFundTransferConfirmYes->setFont(font3);
        pushButtonFundTransferConfirmNo = new QPushButton(N8pageFundTransferConfirm);
        pushButtonFundTransferConfirmNo->setObjectName(QStringLiteral("pushButtonFundTransferConfirmNo"));
        pushButtonFundTransferConfirmNo->setGeometry(QRect(1110, 800, 221, 91));
        pushButtonFundTransferConfirmNo->setFont(font3);
        frame = new QFrame(N8pageFundTransferConfirm);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(330, 620, 1011, 61));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Raised);
        stackedWidget->addWidget(N8pageFundTransferConfirm);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1600, 26));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "Please enter you card to RFID reader", Q_NULLPTR));
        pushButtonSWER->setText(QString());
        pushButtonFIN->setText(QString());
        pushButtonBR->setText(QString());
        pushButton1->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        pushButton3->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        pushButton2->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        pushButton9->setText(QApplication::translate("MainWindow", "9", Q_NULLPTR));
        pushButtonCancel->setText(QApplication::translate("MainWindow", "CANCEL", Q_NULLPTR));
        pushButton8->setText(QApplication::translate("MainWindow", "8", Q_NULLPTR));
        pushButton4->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        pushButton5->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        pushButton7->setText(QApplication::translate("MainWindow", "7", Q_NULLPTR));
        passwordLabel->setText(QString());
        pushButtonLogin->setText(QApplication::translate("MainWindow", "LOGIN", Q_NULLPTR));
        pushButton6->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        attemptsLabelNumber->setText(QString());
        attemptsLabelText->setText(QString());
        pushButtonSWER_2->setText(QString());
        pushButtonBR_2->setText(QString());
        pushButtonFIN_2->setText(QString());
        label_2->setText(QApplication::translate("MainWindow", "Are you sure you want to withdraw", Q_NULLPTR));
        labelWithdrawalConfirm->setText(QString());
        pushButtonWithdrawalConfirmNo->setText(QApplication::translate("MainWindow", "NO", Q_NULLPTR));
        pushButtonWithdrawalConfirmYes->setText(QApplication::translate("MainWindow", "YES", Q_NULLPTR));
        labelWithdrawalConfirm_2->setText(QApplication::translate("MainWindow", "from account", Q_NULLPTR));
        labelWithdrawalSelectedAccount->setText(QString());
        pushButtonWithdrawalMENU->setText(QApplication::translate("MainWindow", "Withdrawal", Q_NULLPTR));
        pushButtonTransactionHistoryMENU->setText(QApplication::translate("MainWindow", "Transaction history", Q_NULLPTR));
        pushButtonAccountsMENU->setText(QApplication::translate("MainWindow", "Accounts", Q_NULLPTR));
        pushButtonFundTransferMENU->setText(QApplication::translate("MainWindow", "Fund Transfer", Q_NULLPTR));
        pushButtonLogout->setText(QApplication::translate("MainWindow", "LOGOUT", Q_NULLPTR));
        pushButtonSWER_3->setText(QString());
        pushButtonFIN_3->setText(QString());
        pushButtonBR_3->setText(QString());
        labelTransactionHistory->setText(QApplication::translate("MainWindow", "Transaction History", Q_NULLPTR));
        pushButtonTransactionHistoryBack->setText(QApplication::translate("MainWindow", "BACK", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "SELECT AMOUNT", Q_NULLPTR));
        pushButtonWithdrawal20->setText(QApplication::translate("MainWindow", "20", Q_NULLPTR));
        pushButtonWithdrawal50->setText(QApplication::translate("MainWindow", "50", Q_NULLPTR));
        pushButtonWithdrawal100->setText(QApplication::translate("MainWindow", "100", Q_NULLPTR));
        pushButtonWithdrawal500->setText(QApplication::translate("MainWindow", "500", Q_NULLPTR));
        pushButtonWithdrawal200->setText(QApplication::translate("MainWindow", "200", Q_NULLPTR));
        pushButtonWithdrawal150->setText(QApplication::translate("MainWindow", "150", Q_NULLPTR));
        pushButtonWithdrawalConfirm->setText(QApplication::translate("MainWindow", "CONFIRM", Q_NULLPTR));
        pushButtonWithdrawalCancel->setText(QApplication::translate("MainWindow", "CANCEL", Q_NULLPTR));
        labelWithdrawalAmount->setText(QString());
        pushButtonWithdrawalBack->setText(QApplication::translate("MainWindow", "BACK", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "SELECT ACCOUNT", Q_NULLPTR));
        labelSelectedAccountWithdrawal->setText(QString());
        label_4->setText(QApplication::translate("MainWindow", "Fund Transfer", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "Select accounts", Q_NULLPTR));
        toolButton->setText(QApplication::translate("MainWindow", "...", Q_NULLPTR));
        pushButtonFundTransferBack->setText(QApplication::translate("MainWindow", "BACK", Q_NULLPTR));
        pushButtonFundTransfer_3->setText(QApplication::translate("MainWindow", "3", Q_NULLPTR));
        pushButtonFundTransfer_1->setText(QApplication::translate("MainWindow", "1", Q_NULLPTR));
        pushButtonFundTransfer_2->setText(QApplication::translate("MainWindow", "2", Q_NULLPTR));
        pushButtonFundTransfer_5->setText(QApplication::translate("MainWindow", "5", Q_NULLPTR));
        pushButtonFundTransfer_6->setText(QApplication::translate("MainWindow", "6", Q_NULLPTR));
        pushButtonFundTransfer_4->setText(QApplication::translate("MainWindow", "4", Q_NULLPTR));
        pushButtonFundTransfer_8->setText(QApplication::translate("MainWindow", "8", Q_NULLPTR));
        pushButtonFundTransfer_9->setText(QApplication::translate("MainWindow", "9", Q_NULLPTR));
        pushButtonFundTransfer_7->setText(QApplication::translate("MainWindow", "7", Q_NULLPTR));
        lineEditTransferAmount->setText(QApplication::translate("MainWindow", "Select transfer amount", Q_NULLPTR));
        pushButtonFundTransfer_return->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        pushButtonFundTransfer_cancel->setText(QApplication::translate("MainWindow", "CANCEL", Q_NULLPTR));
        pushButtonFundTransfer_confirm->setText(QApplication::translate("MainWindow", "CONFIRM", Q_NULLPTR));
        pushButtonFundTransfer_0->setText(QApplication::translate("MainWindow", "0", Q_NULLPTR));
        pushButtonTransferFundsSwap->setText(QString());
        label_6->setText(QApplication::translate("MainWindow", "Accounts", Q_NULLPTR));
        pushButtonAccountsBack->setText(QApplication::translate("MainWindow", "BACK", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "Are you sure you want to transfer", Q_NULLPTR));
        labelTransferAmount->setText(QString());
        label_8->setText(QApplication::translate("MainWindow", "From account", Q_NULLPTR));
        label_Account1->setText(QString());
        label_10->setText(QApplication::translate("MainWindow", "to account", Q_NULLPTR));
        label_Account2->setText(QString());
        pushButtonFundTransferConfirmYes->setText(QApplication::translate("MainWindow", "YES", Q_NULLPTR));
        pushButtonFundTransferConfirmNo->setText(QApplication::translate("MainWindow", "NO", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
